<?php

namespace ContainerHvyxdw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MBV8LzjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mBV8Lzj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mBV8Lzj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'biome' => ['privates', '.errored..service_locator.mBV8Lzj.App\\Entity\\Biome', NULL, 'Cannot autowire service ".service_locator.mBV8Lzj": it needs an instance of "App\\Entity\\Biome" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'biome' => 'App\\Entity\\Biome',
            'entityManager' => '?',
        ]);
    }
}
