<?php

namespace ContainerHvyxdw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZtShSqaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ztShSqa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ztShSqa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formatChambre' => ['privates', 'App\\Repository\\FormatChambreRepository', 'getFormatChambreRepositoryService', true],
        ], [
            'formatChambre' => 'App\\Repository\\FormatChambreRepository',
        ]);
    }
}
