<?php

namespace ContainerHvyxdw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DVQNOsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._dVQNOs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._dVQNOs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formatBilletRepository' => ['privates', 'App\\Repository\\FormatBilletRepository', 'getFormatBilletRepositoryService', true],
        ], [
            'formatBilletRepository' => 'App\\Repository\\FormatBilletRepository',
        ]);
    }
}
