<?php

namespace ContainerHvyxdw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LmNsZooService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lmNsZoo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lmNsZoo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dinosaureRepository' => ['privates', 'App\\Repository\\DinosaureRepository', 'getDinosaureRepositoryService', true],
        ], [
            'dinosaureRepository' => 'App\\Repository\\DinosaureRepository',
        ]);
    }
}
