<?php

namespace ContainerHvyxdw9;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6L1CHUVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6L1CHUV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6L1CHUV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'horaire' => ['privates', '.errored..service_locator.6L1CHUV.App\\Entity\\Horaire', NULL, 'Cannot autowire service ".service_locator.6L1CHUV": it needs an instance of "App\\Entity\\Horaire" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'horaire' => 'App\\Entity\\Horaire',
        ]);
    }
}
