<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \App\Entity\Client implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adressePostal' => [parent::class, 'adressePostal', null, 16],
        "\0".parent::class."\0".'codePostal' => [parent::class, 'codePostal', null, 16],
        "\0".parent::class."\0".'lesBillets' => [parent::class, 'lesBillets', null, 16],
        "\0".parent::class."\0".'lesRestaurants' => [parent::class, 'lesRestaurants', null, 16],
        "\0".parent::class."\0".'otp' => [parent::class, 'otp', null, 16],
        "\0".parent::class."\0".'produitsAchetes' => [parent::class, 'produitsAchetes', null, 16],
        "\0".parent::class."\0".'remboursements' => [parent::class, 'remboursements', null, 16],
        "\0".parent::class."\0".'sejoursHotels' => [parent::class, 'sejoursHotels', null, 16],
        "\0".'App\\Entity\\User'."\0".'email' => ['App\\Entity\\User', 'email', null, 16],
        "\0".'App\\Entity\\User'."\0".'id' => ['App\\Entity\\User', 'id', null, 16],
        "\0".'App\\Entity\\User'."\0".'isVerified' => ['App\\Entity\\User', 'isVerified', null, 16],
        "\0".'App\\Entity\\User'."\0".'nom' => ['App\\Entity\\User', 'nom', null, 16],
        "\0".'App\\Entity\\User'."\0".'numeroTelephone' => ['App\\Entity\\User', 'numeroTelephone', null, 16],
        "\0".'App\\Entity\\User'."\0".'password' => ['App\\Entity\\User', 'password', null, 16],
        "\0".'App\\Entity\\User'."\0".'payerBillets' => ['App\\Entity\\User', 'payerBillets', null, 16],
        "\0".'App\\Entity\\User'."\0".'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        "\0".'App\\Entity\\User'."\0".'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        "\0".'App\\Entity\\User'."\0".'resetTokenExpiration' => ['App\\Entity\\User', 'resetTokenExpiration', null, 16],
        "\0".'App\\Entity\\User'."\0".'roles' => ['App\\Entity\\User', 'roles', null, 16],
        'adressePostal' => [parent::class, 'adressePostal', null, 16],
        'codePostal' => [parent::class, 'codePostal', null, 16],
        'email' => ['App\\Entity\\User', 'email', null, 16],
        'id' => ['App\\Entity\\User', 'id', null, 16],
        'isVerified' => ['App\\Entity\\User', 'isVerified', null, 16],
        'lesBillets' => [parent::class, 'lesBillets', null, 16],
        'lesRestaurants' => [parent::class, 'lesRestaurants', null, 16],
        'nom' => ['App\\Entity\\User', 'nom', null, 16],
        'numeroTelephone' => ['App\\Entity\\User', 'numeroTelephone', null, 16],
        'otp' => [parent::class, 'otp', null, 16],
        'password' => ['App\\Entity\\User', 'password', null, 16],
        'payerBillets' => ['App\\Entity\\User', 'payerBillets', null, 16],
        'prenom' => ['App\\Entity\\User', 'prenom', null, 16],
        'produitsAchetes' => [parent::class, 'produitsAchetes', null, 16],
        'remboursements' => [parent::class, 'remboursements', null, 16],
        'resetToken' => ['App\\Entity\\User', 'resetToken', null, 16],
        'resetTokenExpiration' => ['App\\Entity\\User', 'resetTokenExpiration', null, 16],
        'roles' => ['App\\Entity\\User', 'roles', null, 16],
        'sejoursHotels' => [parent::class, 'sejoursHotels', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
