<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FormatBillet extends \App\Entity\FormatBillet implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'descriptionBillet' => [parent::class, 'descriptionBillet', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageBillet' => [parent::class, 'imageBillet', null, 16],
        "\0".parent::class."\0".'lesAchats' => [parent::class, 'lesAchats', null, 16],
        "\0".parent::class."\0".'libelleBillet' => [parent::class, 'libelleBillet', null, 16],
        "\0".parent::class."\0".'prixBillet' => [parent::class, 'prixBillet', null, 16],
        'descriptionBillet' => [parent::class, 'descriptionBillet', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageBillet' => [parent::class, 'imageBillet', null, 16],
        'lesAchats' => [parent::class, 'lesAchats', null, 16],
        'libelleBillet' => [parent::class, 'libelleBillet', null, 16],
        'prixBillet' => [parent::class, 'prixBillet', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
