<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \App\Entity\Hotel implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'biome' => [parent::class, 'biome', null, 16],
        "\0".parent::class."\0".'descriptionHotel' => [parent::class, 'descriptionHotel', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'imageHotel' => [parent::class, 'imageHotel', null, 16],
        "\0".parent::class."\0".'lesChambres' => [parent::class, 'lesChambres', null, 16],
        "\0".parent::class."\0".'libelleHotel' => [parent::class, 'libelleHotel', null, 16],
        'biome' => [parent::class, 'biome', null, 16],
        'descriptionHotel' => [parent::class, 'descriptionHotel', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'imageHotel' => [parent::class, 'imageHotel', null, 16],
        'lesChambres' => [parent::class, 'lesChambres', null, 16],
        'libelleHotel' => [parent::class, 'libelleHotel', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
