<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chambre extends \App\Entity\Chambre implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'etageChambre' => [parent::class, 'etageChambre', null, 16],
        "\0".parent::class."\0".'formatChambre' => [parent::class, 'formatChambre', null, 16],
        "\0".parent::class."\0".'hotel' => [parent::class, 'hotel', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'lesLocations' => [parent::class, 'lesLocations', null, 16],
        "\0".parent::class."\0".'numeroChambre' => [parent::class, 'numeroChambre', null, 16],
        'etageChambre' => [parent::class, 'etageChambre', null, 16],
        'formatChambre' => [parent::class, 'formatChambre', null, 16],
        'hotel' => [parent::class, 'hotel', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'lesLocations' => [parent::class, 'lesLocations', null, 16],
        'numeroChambre' => [parent::class, 'numeroChambre', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
