<?php

namespace ContainerUnd76hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UlOUAeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ul_oUAe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ul_oUAe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'remboursementRepository' => ['privates', 'App\\Repository\\RemboursementRepository', 'getRemboursementRepositoryService', true],
        ], [
            'entityManager' => '?',
            'remboursementRepository' => 'App\\Repository\\RemboursementRepository',
        ]);
    }
}
