<?php

namespace ContainerUnd76hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6j8EvHHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6j8EvHH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6j8EvHH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'louerHotelRepository' => ['privates', 'App\\Repository\\LouerHotelRepository', 'getLouerHotelRepositoryService', true],
            'ouvertureRestaurantRepository' => ['privates', 'App\\Repository\\OuvertureRestaurantRepository', 'getOuvertureRestaurantRepositoryService', true],
        ], [
            'louerHotelRepository' => 'App\\Repository\\LouerHotelRepository',
            'ouvertureRestaurantRepository' => 'App\\Repository\\OuvertureRestaurantRepository',
        ]);
    }
}
