<?php

namespace ContainerUnd76hb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRemboursementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zNn_71U.App\Entity\Remboursement' shared service.
     *
     * @return \App\Entity\Remboursement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zNn_71U": it needs an instance of "App\\Entity\\Remboursement" but this type has been excluded in "config/services.yaml".');
    }
}
