<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZcZxoQ3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zcZxoQ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zcZxoQ3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chambreRepository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
            'hotelRepository' => ['privates', 'App\\Repository\\HotelRepository', 'getHotelRepositoryService', true],
            'louerHotelRepository' => ['privates', 'App\\Repository\\LouerHotelRepository', 'getLouerHotelRepositoryService', true],
        ], [
            'chambreRepository' => 'App\\Repository\\ChambreRepository',
            'hotelRepository' => 'App\\Repository\\HotelRepository',
            'louerHotelRepository' => 'App\\Repository\\LouerHotelRepository',
        ]);
    }
}
