<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OE3aTRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OE3aT_R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OE3aT_R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dinosaure' => ['privates', '.errored..service_locator.OE3aT_R.App\\Entity\\Dinosaure', NULL, 'Cannot autowire service ".service_locator.OE3aT_R": it needs an instance of "App\\Entity\\Dinosaure" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dinosaure' => 'App\\Entity\\Dinosaure',
            'entityManager' => '?',
        ]);
    }
}
