<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ClqSN3RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ClqSN3R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ClqSN3R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enclosRepository' => ['privates', 'App\\Repository\\EnclosRepository', 'getEnclosRepositoryService', true],
        ], [
            'enclosRepository' => 'App\\Repository\\EnclosRepository',
        ]);
    }
}
