<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WMThnEZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WMThnEZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WMThnEZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chambreRepository' => ['privates', 'App\\Repository\\ChambreRepository', 'getChambreRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'formatBilletRepository' => ['privates', 'App\\Repository\\FormatBilletRepository', 'getFormatBilletRepositoryService', true],
            'formatChambreRepository' => ['privates', 'App\\Repository\\FormatChambreRepository', 'getFormatChambreRepositoryService', true],
            'hotelRepository' => ['privates', 'App\\Repository\\HotelRepository', 'getHotelRepositoryService', true],
            'mailerInterface' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'chambreRepository' => 'App\\Repository\\ChambreRepository',
            'entityManager' => '?',
            'formatBilletRepository' => 'App\\Repository\\FormatBilletRepository',
            'formatChambreRepository' => 'App\\Repository\\FormatChambreRepository',
            'hotelRepository' => 'App\\Repository\\HotelRepository',
            'mailerInterface' => '?',
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
        ]);
    }
}
