<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Tgg2bwoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tgg2bwo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tgg2bwo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'payerBillet' => ['privates', '.errored..service_locator.Tgg2bwo.App\\Entity\\PayerBillet', NULL, 'Cannot autowire service ".service_locator.Tgg2bwo": it needs an instance of "App\\Entity\\PayerBillet" but this type has been excluded in "config/services.yaml".'],
            'remboursementRepository' => ['privates', 'App\\Repository\\RemboursementRepository', 'getRemboursementRepositoryService', true],
        ], [
            'entityManager' => '?',
            'payerBillet' => 'App\\Entity\\PayerBillet',
            'remboursementRepository' => 'App\\Repository\\RemboursementRepository',
        ]);
    }
}
