<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_InUPqQXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.inUPqQX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.inUPqQX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formatBilletRepository' => ['privates', 'App\\Repository\\FormatBilletRepository', 'getFormatBilletRepositoryService', true],
            'formatChambreRepository' => ['privates', 'App\\Repository\\FormatChambreRepository', 'getFormatChambreRepositoryService', true],
            'hotelRepository' => ['privates', 'App\\Repository\\HotelRepository', 'getHotelRepositoryService', true],
            'restaurantRepository' => ['privates', 'App\\Repository\\RestaurantRepository', 'getRestaurantRepositoryService', true],
        ], [
            'formatBilletRepository' => 'App\\Repository\\FormatBilletRepository',
            'formatChambreRepository' => 'App\\Repository\\FormatChambreRepository',
            'hotelRepository' => 'App\\Repository\\HotelRepository',
            'restaurantRepository' => 'App\\Repository\\RestaurantRepository',
        ]);
    }
}
