<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBiomeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mBV8Lzj.App\Entity\Biome' shared service.
     *
     * @return \App\Entity\Biome
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mBV8Lzj": it needs an instance of "App\\Entity\\Biome" but this type has been excluded in "config/services.yaml".');
    }
}
