<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDinosaureService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OE3aT_R.App\Entity\Dinosaure' shared service.
     *
     * @return \App\Entity\Dinosaure
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OE3aT_R": it needs an instance of "App\\Entity\\Dinosaure" but this type has been excluded in "config/services.yaml".');
    }
}
