<?php

namespace ContainerUSg4Jyc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormatChambreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5w3tvi..App\Entity\FormatChambre' shared service.
     *
     * @return \App\Entity\FormatChambre
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5w3tvi.": it needs an instance of "App\\Entity\\FormatChambre" but this type has been excluded in "config/services.yaml".');
    }
}
