<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUnd76hb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUnd76hb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUnd76hb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUnd76hb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUnd76hb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Und76hb',
    'container.build_id' => 'b855f3ea',
    'container.build_time' => 1743618014,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUnd76hb');
